name: Sync Branches

on:
  workflow_dispatch: # Tạo nút "Run workflow" trên GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Chiều 1: Tạo PR từ main sang develop
      - name: PR main to develop
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main"
          destination_branch: "develop"
          pr_title: "Sync: main -> develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Chiều 2: Tạo PR từ develop sang main
      - name: PR develop to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "main"
          pr_title: "Sync: develop -> main"
          github_token: ${{ secrets.GITHUB_TOKEN }}